### ISSUE TITLE
composer.json require section is not taken into account when linking package

### ISSUE THREAD

**Issue by develop-bvi106** [SanderSander/composer-link#61]
Hi,
i'm using this awesome plugin for our local development.

Let's say i have `PROJECT1` using `PACKAGE1` via composer link, after having installed new dependencies on `PACKAGE1`, the `composer dump-autoload` in PROJECT1 doesnt see new dependencies installed and doesn't autoload new modules.

I've noted that, also after `composer update PACKAGE1`, the `composer.lock` `require` section is not updated using the require section of the **local** `COMPONENT1` but seems it's using the **published** package dependencies on Packagist, it does update the composer.lock hash but doesn't reflect the required dependencies changes in the parent composer.lock file.

We have many others dependencies in PACKAGE1 composer.json\require (already published on Packagist) that are loaded correctly from the parent project.

Maybe i'm missing something or have messed up with package dependencies, any help would be greatly appreciated!

**Comment by ashooner** [comment]
We have the same issue. This is really a great tool; but our problem use case is when we change a `require` entry in a linked package's composer.json file, that local change is not respected by the `composer install` on the root package. If composer-link is just managing aliases, this makes sense, since composer (apparently) will refer to the package's repository for metadata while resolving the dependency tree.

My thought was to have composer-link dynamically replace the linked package's repository with a local path-based repository, which (again, I assume) would make composer respect the local composer.json file, and its changes. I'm just starting to review it, but it looks like composer link does this, or something like it, already. I'm not at all familiar with Composer's api, so kind of feeling around in the dark.

**Comment by SanderSander** [comment]
This weekend I should have time to look into this. I think I will be able to create some tests for this, and hopefully resolve the issue afterwards.

**Comment by ashooner** [comment]
Thanks for the prompt reply! What you describe would meet our requirements, although it would involve re-linking if the `package2` version changed in the course of development. 

It looks like you have a lot of work into this approach already, but just to brainstorm:  last night I started to look at subscribing to `pre-install-cmd` and `pre-update-cmd` events, and actually generate dynamic path type repositories, based on linked packages. I think that would allow composer to refer to the local `package1` `composer.json` file directly without additional dependency resolution logic. However, this would mean  changing the `composer.lock` file, which it sounds like you'd prefer to avoid. The lock file is ephemeral in our use case so that wouldn't be an issue.

**Comment by SanderSander** [comment]
> Thanks for the prompt reply! What you describe would meet our requirements, although it would involve re-linking if the `package2` version changed in the course of development.

Yes so changes in the dependencies of the linked packages will require a new `composer install` or re-linking the package, there is simply no way to detect those changes otherwise (maybe there are but way to impact full on the system).

> It looks like you have a lot of work into this approach already, but just to brainstorm: last night I started to look at subscribing to `pre-install-cmd` and `pre-update-cmd` events, and actually generate dynamic path type repositories, based on linked packages. I think that would allow composer to refer to the local `package1` `composer.json` file directly without additional dependency resolution logic. However, this would mean changing the `composer.lock` file, which it sounds like you'd prefer to avoid. The lock file is ephemeral in our use case so that wouldn't be an issue.

Yes, because for most projects it's import to commit the lock file and also a good amount of libraries choose to commit their lock file, so this tool is really for development purpose to make easy changes/bugfixes in an included libraries.

In composer you could also define path repositories as described here: 
https://getcomposer.org/doc/05-repositories.md#path
which will symlink you packages into your project and also install all required dependencies, but this requires altering your `composer.json` file, and after the install your `composer.lock` will also be changed.

**Comment by fbramato** [comment]
@SanderSander sounds perfect to us, is exactly what we need for.

Meanwhile we found a workaround: commiting the modified branch with new dependencies on github and modifying composer.json in parent project, did the trick

```
"repositories": [
        {
            "type": "composer",
            "url": "https://repo.packagist.com/org/",
            "only": [
                "bvi/*"
            ]
        },
        {
            "type": "git",
            "url": "git@github.com:org/framework.git",
            "only": [
                "org/framework"
            ]
        }
    ],
```

and then reference the package version as:
` "org/framework": "dev-other-branch",`

launching composer update org/framework actually updates correctly the parent project `composer.json` and .lock and also the composer classes autoload

**Comment by austenc** [comment]
Hey @SanderSander sorry to bother you, but could you elaborate on how you think a solution to this might work, or share some WIP code (or a branch name?). 

I'd be happy to try making a PR for this because it would be super, super nice to have. Thank you!

**Comment by SanderSander** [comment]
> Hey @SanderSander sorry to bother you, but could you elaborate on how you think a solution to this might work, or share some WIP code (or a branch name?).
> 
> I'd be happy to try making a PR for this because it would be super, super nice to have. Thank you!
> 
> Edit: just found #47 -- are you still interested in this feature?

Hey, 

My first thought is to simply add an extra flag as example `composer link ../some-package --with-dependencies` but 
there are a few things that have to be kept in mind:

 - I think we shouldn't change the current behavior, it will change the work flow of people that are using the plugin. In the future we could change the behavior by adding a flag `--without-dependencies` but we have to inform the users before that point.

 - We have to deal with incompatible changes somehow, as example in a project we have `package-a` that depends on `some-package: ^1.0` and we have a `package-b` that also depends on that `some-package: ^1.0` if we link `package-b` with some updated dependencies and it changed to  `some-package: ^2.0` we need to inform the user (I think we can use the default error messages of composer aka let composer do his thing) and after the error we rollback the linked packages to a non-linked state.  
 
 - We have to track which packages are linked and which ones not. Currently there is a JSON file that tracks information about the linked packages in `vendor/linked-packages.json` this is handled by the following classes `Repository/Transformer` and `Respository/Respository` 

- It would be nice if `composer linked` command provides information about which packages are linked with dependencies and which one are not.

**Comment by SanderSander** [comment]
> Hey @SanderSander sorry to bother you, but could you elaborate on how you think a solution to this might work, or share some WIP code (or a branch name?).
> 
> I'd be happy to try making a PR for this because it would be super, super nice to have. Thank you!
> 
> Edit: just found #47 -- are you still interested in this feature?

Hey, 

My first thought is to simply add an extra flag as example `composer link ../some-package --with-dependencies` but 
there are a few things that have to be kept in mind:

 - I think we shouldn't change the current behavior, it will change the work flow of people that are using the plugin. In the future we could change the behavior by adding a flag `--without-dependencies` but we have to inform the users before that point.

 - We have to deal with incompatible changes somehow, as example in a project we have `package-a` that depends on `some-package: ^1.0` and we have a `package-b` that also depends on that `some-package: ^1.0` if we link `package-b` with some updated dependencies and it changed to  `some-package: ^2.0` we need to inform the user (I think we can use the default error messages of composer aka let composer do his thing) and after the error we rollback the linked packages to a non-linked state.  
 
 - We have to track which packages are linked and which ones not. Currently there is a JSON file that tracks information about the linked packages in `vendor/linked-packages.json` this is handled by the following classes `Repository/Transformer` and `Respository/Respository` 

- It would be nice if `composer linked` command provides information about which packages are linked with dependencies and which ones are not. 

- We have to make sure that the `composer.lock` file doesn't reflect the changes by the linked packages, I think it's important to write some integration tests for this. 

These are my initial thoughts about it, so feel free to help :) it would be really appreciated. 
Tomorrow I got some free time (and will release a new version with PHP 8.4 support), and I will take a bit deeper look into it.

**Comment by SanderSander** [comment]
Woop got a working version in the attached PR! 🥳 🥳 🥳 🥳 

It still needs some work, but it's working, I hope I'm able to finish it up this weekend

**Comment by austenc** [comment]
Dang, that was fast, thank you in advance @SanderSander! This is a tricky feature, but will be amazing to have. Appreciate your work on this very much! 🍻

**Comment by SanderSander** [comment]
I have everything merged on `dev-master` I still want to use it a few days before I release a tag (Still hitting some bugs at times, but I think I got most now). 

I will release it next week in version 0.5.0 and 🤞🏻
